// app/api/projects/[cityName]/route.js
import { NextResponse } from 'next/server'

// Mock data for testing
const mockProjects = {
  mumbai: [
    {
      id: 'mumbai_1',
      name: 'Lodha Park',
      location: 'Lower Parel',
      builder: 'Lodha Group',
      price: '₹2.5 Cr - ₹8.5 Cr',
      area: '1, 2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 19.0144, lng: 72.8317 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_2',
      name: 'Oberoi Sky City',
      location: 'Worli',
      builder: 'Oberoi Realty',
      price: '₹4.2 Cr - ₹12.5 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 19.0176, lng: 72.8162 },
      amenities: ['Club House', 'Swimming Pool', 'Spa'],
      image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_3',
      name: 'Raheja Atlantis',
      location: 'Prabhadevi',
      builder: 'K Raheja Corp',
      price: '₹3.8 Cr - ₹9.2 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 19.0138, lng: 72.8300 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_4',
      name: 'Godrej The Trees',
      location: 'Vikhroli East',
      builder: 'Godrej Properties',
      price: '₹1.8 Cr - ₹4.5 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 19.1095, lng: 72.9240 },
      amenities: ['Swimming Pool', 'Gym', 'Park', 'Security'],
      image: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_5',
      name: 'Hiranandani Gardens',
      location: 'Powai',
      builder: 'Hiranandani Group',
      price: '₹2.2 Cr - ₹6.8 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 19.1197, lng: 72.9063 },
      amenities: ['Lake View', 'Swimming Pool', 'Club House', 'Tennis Court'],
      image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_6',
      name: 'Shapoorji Pallonji Mumbai',
      location: 'Kandivali East',
      builder: 'Shapoorji Pallonji',
      price: '₹1.5 Cr - ₹3.8 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 19.2095, lng: 72.8634 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_7',
      name: 'Tata Housing Primanti',
      location: 'Bhandup West',
      builder: 'Tata Housing',
      price: '₹1.2 Cr - ₹2.8 Cr',
      area: '1, 2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 19.0583, lng: 72.8342 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_8',
      name: 'Mahindra Lifespaces',
      location: 'Bhandup West',
      builder: 'Mahindra Lifespace',
      price: '₹1.8 Cr - ₹4.2 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 19.1465, lng: 72.9380 },
      amenities: ['Swimming Pool', 'Gym', 'Park', 'Security'],
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_9',
      name: 'L&T Emerald Isle',
      location: 'Powai',
      builder: 'L&T Realty',
      price: '₹3.5 Cr - ₹8.5 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 19.1176, lng: 72.9060 },
      amenities: ['Lake View', 'Swimming Pool', 'Club House', 'Tennis Court'],
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_10',
      name: 'Piramal Mahalaxmi',
      location: 'Mahalaxmi',
      builder: 'Piramal Realty',
      price: '₹8.5 Cr - ₹25 Cr',
      area: '3, 4, 5 BHK',
      status: 'Under Construction',
      coordinates: { lat: 18.9847, lng: 72.8206 },
      amenities: ['Sea View', 'Swimming Pool', 'Spa', 'Concierge'],
      image: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?ixlib=rb-4.0.3'
    }
  ],
  delhi: [
    {
      id: 'delhi_1',
      name: 'DLF The Camellias',
      location: 'Sector 42, Gurgaon',
      builder: 'DLF Limited',
      price: '₹8 Cr - ₹25 Cr',
      area: '3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.4403, lng: 77.0637 },
      amenities: ['Golf Course', 'Swimming Pool', 'Spa', 'Security'],
      image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_2',
      name: 'Godrej South Estate',
      location: 'Sector 150, Noida',
      builder: 'Godrej Properties',
      price: '₹1.2 Cr - ₹3.8 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.5021, lng: 77.4086 },
      amenities: ['Swimming Pool', 'Gym', 'Park', 'Security'],
      image: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_3',
      name: 'M3M Golf Estate',
      location: 'Sector 65, Gurgaon',
      builder: 'M3M Group',
      price: '₹2.5 Cr - ₹8.5 Cr',
      area: '3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.3952, lng: 77.0463 },
      amenities: ['Golf Course', 'Swimming Pool', 'Club House', 'Security'],
      image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_4',
      name: 'Sobha City',
      location: 'Sector 108, Gurgaon',
      builder: 'Sobha Limited',
      price: '₹1.8 Cr - ₹5.2 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.4089, lng: 77.0507 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_5',
      name: 'Emaar Palm Hills',
      location: 'Sector 77, Gurgaon',
      builder: 'Emaar India',
      price: '₹3.2 Cr - ₹9.8 Cr',
      area: '3, 4, 5 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.3894, lng: 77.0683 },
      amenities: ['Swimming Pool', 'Gym', 'Golf Course', 'Security'],
      image: 'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_6',
      name: 'Tata Primanti',
      location: 'Sector 72, Gurgaon',
      builder: 'Tata Housing',
      price: '₹1.5 Cr - ₹4.2 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.3742, lng: 77.0895 },
      amenities: ['Swimming Pool', 'Gym', 'Park', 'Security'],
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_7',
      name: 'Unitech The Residences',
      location: 'Sector 33, Gurgaon',
      builder: 'Unitech Limited',
      price: '₹3.8 Cr - ₹9.5 Cr',
      area: '3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.4294, lng: 77.0688 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_8',
      name: 'Ireo Victory Valley',
      location: 'Sector 67, Gurgaon',
      builder: 'Ireo Private Limited',
      price: '₹4.5 Cr - ₹12.8 Cr',
      area: '3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.3900, lng: 77.0700 },
      amenities: ['Golf Course', 'Swimming Pool', 'Spa', 'Club House'],
      image: 'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_9',
      name: 'BPTP Park Serene',
      location: 'Sector 37D, Gurgaon',
      builder: 'BPTP Limited',
      price: '₹2.1 Cr - ₹5.8 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.4200, lng: 77.0650 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Children Play Area'],
      image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_10',
      name: 'Ansal Heights',
      location: 'Sector 92, Gurgaon',
      builder: 'Ansal API',
      price: '₹1.8 Cr - ₹4.5 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.4000, lng: 77.0600 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3'
    }
  ],
  ghaziabad: [
    {
      id: 'ghaziabad_1',
      name: 'Supertech Cape Town',
      location: 'Sector 74',
      builder: 'Supertech Limited',
      price: '₹85 Lac - ₹1.5 Cr',
      area: '2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.6017, lng: 77.4085 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3'
    },
    {
      id: 'ghaziabad_2',
      name: 'Mahagun Moderne',
      location: 'Sector 78',
      builder: 'Mahagun Group',
      price: '₹95 Lac - ₹2.1 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.6139, lng: 77.4270 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Security'],
      image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3'
    },
    {
      id: 'ghaziabad_3',
      name: 'ATS Pristine',
      location: 'Sector 150',
      builder: 'ATS Infrastructure',
      price: '₹1.2 Cr - ₹2.8 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.6292, lng: 77.3910 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Tennis Court'],
      image: 'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?ixlib=rb-4.0.3'
    },
    {
      id: 'ghaziabad_4',
      name: 'Gaur City 2',
      location: 'Sector 16C',
      builder: 'Gaursons Group',
      price: '₹65 Lac - ₹1.8 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.6127, lng: 77.4238 },
      amenities: ['Swimming Pool', 'Gym', 'Shopping Mall', 'Security'],
      image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3'
    },
    {
      id: 'ghaziabad_5',
      name: 'Ajnara Homes',
      location: 'Sector 16B',
      builder: 'Ajnara India Ltd',
      price: '₹75 Lac - ₹1.6 Cr',
      area: '2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.6200, lng: 77.4100 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?ixlib=rb-4.0.3'
    },
    {
      id: 'ghaziabad_6',
      name: 'SKA Greenarch',
      location: 'Sector 16C',
      builder: 'SKA Group',
      price: '₹88 Lac - ₹2.2 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.6150, lng: 77.4200 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Children Play Area'],
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3'
    },
    {
      id: 'ghaziabad_7',
      name: 'Paramount Emotions',
      location: 'Sector 1',
      builder: 'Paramount Group',
      price: '₹72 Lac - ₹1.9 Cr',
      area: '2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.6089, lng: 77.4156 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?ixlib=rb-4.0.3'
    },
    {
      id: 'ghaziabad_8',
      name: 'Omaxe The Resort',
      location: 'Mullanpur',
      builder: 'Omaxe Limited',
      price: '₹1.1 Cr - ₹2.5 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.6234, lng: 77.4050 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Spa'],
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
    },
    {
      id: 'ghaziabad_9',
      name: 'Nirala Aspire',
      location: 'Sector 16',
      builder: 'Nirala Group',
      price: '₹78 Lac - ₹1.7 Cr',
      area: '2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.6180, lng: 77.4120 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3'
    },
    {
      id: 'ghaziabad_10',
      name: 'Wave City',
      location: 'NH-24',
      builder: 'Wave Infratech',
      price: '₹1.3 Cr - ₹3.2 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.6300, lng: 77.4000 },
      amenities: ['Swimming Pool', 'Gym', 'Golf Course', 'Club House'],
      image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3'
    }
  ],
  noida: [
    {
      id: 'noida_1',
      name: 'Amrapali Silicon City',
      location: 'Sector 76',
      builder: 'Amrapali Group',
      price: '₹45 Lac - ₹1.2 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.5700, lng: 77.3200 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?ixlib=rb-4.0.3'
    },
    {
      id: 'noida_2',
      name: 'Supertech Eco Village',
      location: 'Sector 1',
      builder: 'Supertech Limited',
      price: '₹65 Lac - ₹1.8 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.5355, lng: 77.3910 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Tennis Court'],
      image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3'
    },
    {
      id: 'noida_3',
      name: 'ATS Knightsbridge',
      location: 'Sector 124',
      builder: 'ATS Infrastructure',
      price: '₹1.8 Cr - ₹4.5 Cr',
      area: '3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.5406, lng: 77.3219 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Golf Course'],
      image: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?ixlib=rb-4.0.3'
    },
    {
      id: 'noida_4',
      name: 'Jaypee Greens',
      location: 'Sector 128',
      builder: 'Jaiprakash Associates',
      price: '₹1.2 Cr - ₹3.5 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.5403, lng: 77.3200 },
      amenities: ['Swimming Pool', 'Gym', 'Golf Course', 'Club House'],
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3'
    },
    {
      id: 'noida_5',
      name: 'Godrej Woods',
      location: 'Sector 43',
      builder: 'Godrej Properties',
      price: '₹2.5 Cr - ₹6.8 Cr',
      area: '3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.5562, lng: 77.3410 },
      amenities: ['Swimming Pool', 'Gym', 'Spa', 'Tennis Court'],
      image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?ixlib=rb-4.0.3'
    },
    {
      id: 'noida_6',
      name: 'Mahagun Mywoods',
      location: 'Sector 16C',
      builder: 'Mahagun Group',
      price: '₹1.6 Cr - ₹4.2 Cr',
      area: '3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.5456, lng: 77.3500 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
    },
    {
      id: 'noida_7',
      name: 'Antriksh Heights',
      location: 'Sector 84',
      builder: 'Antriksh India',
      price: '₹75 Lac - ₹2.1 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.5600, lng: 77.3300 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Children Play Area'],
      image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3'
    },
    {
      id: 'noida_8',
      name: 'Prateek Wisteria',
      location: 'Sector 77',
      builder: 'Prateek Group',
      price: '₹95 Lac - ₹2.8 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.5734, lng: 77.3200 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3'
    },
    {
      id: 'noida_9',
      name: 'Lotus Boulevard',
      location: 'Sector 100',
      builder: 'Lotus Realtech',
      price: '₹1.4 Cr - ₹3.9 Cr',
      area: '3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.5367, lng: 77.3700 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Spa'],
      image: 'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?ixlib=rb-4.0.3'
    },
    {
      id: 'noida_10',
      name: 'Stellar Jeevan',
      location: 'Sector 1',
      builder: 'Stellar Group',
      price: '₹58 Lac - ₹1.5 Cr',
      area: '2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.5389, lng: 77.3950 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3'
    }
  ],
  bangalore: [
    {
      id: 'bangalore_1',
      name: 'Brigade Cornerstone Utopia',
      location: 'Varthur',
      builder: 'Brigade Group',
      price: '₹1.2 Cr - ₹3.8 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 12.9698, lng: 77.7500 },
      amenities: ['Swimming Pool', 'Gym', 'Park', 'Security'],
      image: 'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?ixlib=rb-4.0.3'
    },
    {
      id: 'bangalore_2',
      name: 'Prestige Lakeside Habitat',
      location: 'Varthur',
      builder: 'Prestige Group',
      price: '₹1.8 Cr - ₹4.5 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 12.9716, lng: 77.7946 },
      amenities: ['Lake View', 'Swimming Pool', 'Club House', 'Tennis Court'],
      image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3'
    },
    {
      id: 'bangalore_3',
      name: 'Godrej Reflections',
      location: 'Harlur',
      builder: 'Godrej Properties',
      price: '₹1.5 Cr - ₹3.9 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 12.8970, lng: 77.6934 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3'
    },
    {
      id: 'bangalore_4',
      name: 'Sobha Neopolis',
      location: 'Panathur',
      builder: 'Sobha Limited',
      price: '₹2.2 Cr - ₹5.8 Cr',
      area: '3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 12.9600, lng: 77.6900 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Spa'],
      image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?ixlib=rb-4.0.3'
    },
    {
      id: 'bangalore_5',
      name: 'Mantri Glades',
      location: 'Sarjapur Road',
      builder: 'Mantri Developers',
      price: '₹1.8 Cr - ₹4.2 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 12.9279, lng: 77.6271 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Tennis Court'],
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
    },
    {
      id: 'bangalore_6',
      name: 'Puravankara Zenium',
      location: 'Hosur Road',
      builder: 'Puravankara Limited',
      price: '₹2.5 Cr - ₹6.5 Cr',
      area: '3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 12.9141, lng: 77.6411 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Security'],
      image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3'
    },
    {
      id: 'bangalore_7',
      name: 'Salarpuria Sattva Divinity',
      location: 'Kogilu',
      builder: 'Salarpuria Sattva',
      price: '₹1.4 Cr - ₹3.6 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 13.0827, lng: 77.5946 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Children Play Area'],
      image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3'
    },
    {
      id: 'bangalore_8',
      name: 'Assetz Marq',
      location: 'Kanakpura Road',
      builder: 'Assetz Property Group',
      price: '₹1.6 Cr - ₹4.1 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 12.8546, lng: 77.5679 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Security'],
      image: 'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?ixlib=rb-4.0.3'
    },
    {
      id: 'bangalore_9',
      name: 'Embassy Boulevard',
      location: 'Bagalur',
      builder: 'Embassy Group',
      price: '₹2.8 Cr - ₹7.2 Cr',
      area: '3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 13.0358, lng: 77.6200 },
      amenities: ['Swimming Pool', 'Gym', 'Golf Course', 'Spa'],
      image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3'
    },
    {
      id: 'bangalore_10',
      name: 'Shriram Park 63',
      location: 'Jakkur',
      builder: 'Shriram Properties',
      price: '₹1.3 Cr - ₹3.4 Cr',
      area: '2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 13.0827, lng: 77.6380 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?ixlib=rb-4.0.3'
    }
  ],
  GreaterNoida: [
    {
      id: 'greaternoida_1',
      name: 'Gaur Yamuna City',
      location: 'Sector 19',
      builder: 'Gaursons Group',
      price: '₹35 Lac - ₹85 Lac',
      area: '1, 2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.4744, lng: 77.5040 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3'
    },
    {
      id: 'greaternoida_2',
      name: 'ATS Allure',
      location: 'Sector 22D',
      builder: 'ATS Infrastructure',
      price: '₹75 Lac - ₹1.8 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.4594, lng: 77.5067 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Tennis Court'],
      image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?ixlib=rb-4.0.3'
    },
    {
      id: 'greaternoida_3',
      name: 'Godrej Golf Links',
      location: 'Sector Alpha II',
      builder: 'Godrej Properties',
      price: '₹85 Lac - ₹2.5 Cr',
      area: '2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.4744, lng: 77.5040 },
      amenities: ['Golf Course', 'Swimming Pool', 'Club House', 'Security'],
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
    },
    {
      id: 'greaternoida_4',
      name: 'Supertech Eco Village 2',
      location: 'Sector 16B',
      builder: 'Supertech Limited',
      price: '₹65 Lac - ₹1.6 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.4636, lng: 77.4866 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3'
    },
    {
      id: 'greaternoida_5',
      name: 'Jaypee Greens Kensington Park',
      location: 'Sector 133',
      builder: 'Jaypee Group',
      price: '₹1.1 Cr - ₹2.8 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.4744, lng: 77.5000 },
      amenities: ['Golf Course', 'Swimming Pool', 'Club House', 'Security'],
      image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3'
    },
    {
      id: 'greaternoida_6',
      name: 'Eldeco Utopia',
      location: 'Sector 93A',
      builder: 'Eldeco Group',
      price: '₹78 Lac - ₹1.9 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.4689, lng: 77.5100 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Tennis Court'],
      image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3'
    },
    {
      id: 'greaternoida_7',
      name: 'Ace Divino',
      location: 'Sector 1',
      builder: 'Ace Group',
      price: '₹58 Lac - ₹1.4 Cr',
      area: '2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.4744, lng: 77.5040 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Security'],
      image: 'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?ixlib=rb-4.0.3'
    },
    {
      id: 'greaternoida_8',
      name: 'Stellar Jeevan',
      location: 'Sector Omicron 1A',
      builder: 'Stellar Group',
      price: '₹45 Lac - ₹1.2 Cr',
      area: '1, 2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.4700, lng: 77.5150 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Children Play Area'],
      image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3'
    },
    {
      id: 'greaternoida_9',
      name: 'Mahagun Manorial',
      location: 'Sector 128',
      builder: 'Mahagun Group',
      price: '₹95 Lac - ₹2.2 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.4650, lng: 77.5080 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Spa'],
      image: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?ixlib=rb-4.0.3'
    },
    {
      id: 'greaternoida_10',
      name: 'Antriksh Golf Links',
      location: 'Sector 150',
      builder: 'Antriksh India',
      price: '₹88 Lac - ₹2.1 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.4750, lng: 77.5000 },
      amenities: ['Golf Course', 'Swimming Pool', 'Club House', 'Security'],
      image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?ixlib=rb-4.0.3'
    }
  ],
  pune: [
    {
      id: 'pune_1',
      name: 'Godrej Elements',
      location: 'Hinjewadi',
      builder: 'Godrej Properties',
      price: '₹65 Lac - ₹1.8 Cr',
      area: '2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 18.5904, lng: 73.7394 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3'
    },
    {
      id: 'pune_2',
      name: 'Lodha Belmondo',
      location: 'Kharadi',
      builder: 'Lodha Group',
      price: '₹85 Lac - ₹2.5 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 18.5562, lng: 73.9370 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Tennis Court'],
      image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?ixlib=rb-4.0.3'
    },
    {
      id: 'pune_3',
      name: 'Sobha Rain Forest',
      location: 'Tathawade',
      builder: 'Sobha Limited',
      price: '₹75 Lac - ₹2.1 Cr',
      area: '2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 18.5314, lng: 73.7417 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
    },
    {
      id: 'pune_4',
      name: 'Prestige Song of the South',
      location: 'Undri',
      builder: 'Prestige Group',
      price: '₹95 Lac - ₹2.8 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 18.4683, lng: 73.9428 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Spa'],
      image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3'
    },
    {
      id: 'pune_5',
      name: 'Tata Housing Avenida',
      location: 'New Town',
      builder: 'Tata Housing',
      price: '₹68 Lac - ₹1.9 Cr',
      area: '2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 18.5204, lng: 73.8567 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Children Play Area'],
      image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3'
    },
    {
      id: 'pune_6',
      name: 'Mahindra Lifespace Windchimes',
      location: 'Pimpri Chinchwad',
      builder: 'Mahindra Lifespace',
      price: '₹55 Lac - ₹1.6 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 18.6298, lng: 73.7997 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?ixlib=rb-4.0.3'
    },
    {
      id: 'pune_7',
      name: 'Brigade Cosmopolis',
      location: 'Whitefield',
      builder: 'Brigade Group',
      price: '₹78 Lac - ₹2.2 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 18.5793, lng: 73.9089 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Tennis Court'],
      image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3'
    },
    {
      id: 'pune_8',
      name: 'Kolte Patil Life Republic',
      location: 'Hinjewadi',
      builder: 'Kolte Patil',
      price: '₹88 Lac - ₹2.4 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 18.5904, lng: 73.7394 },
      amenities: ['Swimming Pool', 'Gym', 'Shopping Mall', 'Security'],
      image: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?ixlib=rb-4.0.3'
    },
    {
      id: 'pune_9',
      name: 'Puravankara Purva Windermere',
      location: 'Pallavaram',
      builder: 'Puravankara Limited',
      price: '₹72 Lac - ₹2.0 Cr',
      area: '2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 18.5314, lng: 73.8567 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3'
    },
    {
      id: 'pune_10',
      name: 'Shriram Grand City',
      location: 'Balewadi',
      builder: 'Shriram Properties',
      price: '₹65 Lac - ₹1.8 Cr',
      area: '1, 2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 18.5793, lng: 73.7733 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Children Play Area'],
      image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?ixlib=rb-4.0.3'
    }
  ],
  hyderabad: [
    {
      id: 'hyderabad_1',
      name: 'Godrej Reflections',
      location: 'Harlur',
      builder: 'Godrej Properties',
      price: '₹58 Lac - ₹1.5 Cr',
      area: '2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 17.3850, lng: 78.4867 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
    },
    {
      id: 'hyderabad_2',
      name: 'Prestige Tranquility',
      location: 'Budigere Cross',
      builder: 'Prestige Group',
      price: '₹75 Lac - ₹2.1 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 17.4065, lng: 78.4772 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Tennis Court'],
      image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3'
    },
    {
      id: 'hyderabad_3',
      name: 'Sobha Dream Acres',
      location: 'Thanisandra',
      builder: 'Sobha Limited',
      price: '₹68 Lac - ₹1.9 Cr',
      area: '2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 17.3616, lng: 78.4747 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Spa'],
      image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3'
    },
    {
      id: 'hyderabad_4',
      name: 'Brigade Cornerstone Utopia',
      location: 'Varthur',
      builder: 'Brigade Group',
      price: '₹85 Lac - ₹2.3 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 17.4400, lng: 78.3489 },
      amenities: ['Swimming Pool', 'Gym', 'Park', 'Security'],
      image: 'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?ixlib=rb-4.0.3'
    },
    {
      id: 'hyderabad_5',
      name: 'Tata Housing New Haven',
      location: 'Rajarhat',
      builder: 'Tata Housing',
      price: '₹52 Lac - ₹1.4 Cr',
      area: '2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 17.4851, lng: 78.3967 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3'
    },
    {
      id: 'hyderabad_6',
      name: 'Mahindra Lifespace Bloomdale',
      location: 'Mihan',
      builder: 'Mahindra Lifespace',
      price: '₹45 Lac - ₹1.2 Cr',
      area: '1, 2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 17.3753, lng: 78.4784 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Children Play Area'],
      image: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?ixlib=rb-4.0.3'
    },
    {
      id: 'hyderabad_7',
      name: 'Salarpuria Sattva Greenage',
      location: 'Sholinganallur',
      builder: 'Salarpuria Sattva',
      price: '₹78 Lac - ₹2.0 Cr',
      area: '2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 17.4475, lng: 78.3563 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3'
    },
    {
      id: 'hyderabad_8',
      name: 'Ramky One Galaxia',
      location: 'Barasat',
      builder: 'Ramky Group',
      price: '₹65 Lac - ₹1.7 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 17.3850, lng: 78.4867 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Security'],
      image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?ixlib=rb-4.0.3'
    },
    {
      id: 'hyderabad_9',
      name: 'Lodha Belmondo',
      location: 'Howrah',
      builder: 'Lodha Group',
      price: '₹88 Lac - ₹2.4 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 17.4065, lng: 78.4772 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Spa'],
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
    },
    {
      id: 'hyderabad_10',
      name: 'Shriram Chirping Woods',
      location: 'New Town',
      builder: 'Shriram Properties',
      price: '₹48 Lac - ₹1.3 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 17.3616, lng: 78.4747 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Children Play Area'],
      image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3'
    }
  ],
  mumbai: [
    {
      id: 'mumbai_1',
      name: 'Lodha Park',
      location: 'Lower Parel',
      builder: 'Lodha Group',
      price: '₹2.5 Cr - ₹8.5 Cr',
      area: '1, 2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 19.0144, lng: 72.8317 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_2',
      name: 'Oberoi Sky City',
      location: 'Worli',
      builder: 'Oberoi Realty',
      price: '₹4.2 Cr - ₹12.5 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 19.0176, lng: 72.8162 },
      amenities: ['Club House', 'Swimming Pool', 'Spa'],
      image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_3',
      name: 'Raheja Atlantis',
      location: 'Prabhadevi',
      builder: 'K Raheja Corp',
      price: '₹3.8 Cr - ₹9.2 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 19.0138, lng: 72.8300 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_4',
      name: 'Godrej The Trees',
      location: 'Vikhroli East',
      builder: 'Godrej Properties',
      price: '₹1.8 Cr - ₹4.5 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 19.1095, lng: 72.9240 },
      amenities: ['Swimming Pool', 'Gym', 'Park', 'Security'],
      image: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_5',
      name: 'Hiranandani Gardens',
      location: 'Powai',
      builder: 'Hiranandani Group',
      price: '₹2.2 Cr - ₹6.8 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 19.1197, lng: 72.9063 },
      amenities: ['Lake View', 'Swimming Pool', 'Club House', 'Tennis Court'],
      image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_6',
      name: 'Shapoorji Pallonji Mumbai',
      location: 'Kandivali East',
      builder: 'Shapoorji Pallonji',
      price: '₹1.5 Cr - ₹3.8 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 19.2095, lng: 72.8634 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_7',
      name: 'Tata Housing Primanti',
      location: 'Sector 72, Gurgaon',
      builder: 'Tata Housing',
      price: '₹1.2 Cr - ₹2.8 Cr',
      area: '1, 2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 19.0583, lng: 72.8342 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_8',
      name: 'Mahindra Lifespaces',
      location: 'Bhandup West',
      builder: 'Mahindra Lifespace',
      price: '₹1.8 Cr - ₹4.2 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 19.1465, lng: 72.9380 },
      amenities: ['Swimming Pool', 'Gym', 'Park', 'Security'],
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_9',
      name: 'L&T Emerald Isle',
      location: 'Powai',
      builder: 'L&T Realty',
      price: '₹3.5 Cr - ₹8.5 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 19.1176, lng: 72.9060 },
      amenities: ['Lake View', 'Swimming Pool', 'Club House', 'Tennis Court'],
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_10',
      name: 'Brigade Golden Triangle',
      location: 'Bandra East',
      builder: 'Brigade Group',
      price: '₹4.5 Cr - ₹12.8 Cr',
      area: '3, 4, 5 BHK',
      status: 'Under Construction',
      coordinates: { lat: 19.0596, lng: 72.8526 },
      amenities: ['Swimming Pool', 'Gym', 'Spa', 'Security'],
      image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_11',
      name: 'Prestige White Meadows',
      location: 'Whitefield',
      builder: 'Prestige Group',
      price: '₹2.8 Cr - ₹7.2 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 19.0330, lng: 72.8570 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_12',
      name: 'Runwal Gardens',
      location: 'Dombivli East',
      builder: 'Runwal Group',
      price: '₹85 Lac - ₹2.2 Cr',
      area: '1, 2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 19.2183, lng: 73.0878 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_13',
      name: 'Kalpataru Riverside',
      location: 'Panvel',
      builder: 'Kalpataru Group',
      price: '₹75 Lac - ₹1.8 Cr',
      area: '1, 2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 19.0030, lng: 73.1200 },
      amenities: ['River View', 'Swimming Pool', 'Club House', 'Garden'],
      image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_14',
      name: 'Sobha Dream Acres',
      location: 'Baramati',
      builder: 'Sobha Limited',
      price: '₹1.2 Cr - ₹3.5 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 19.0896, lng: 72.8656 },
      amenities: ['Swimming Pool', 'Gym', 'Park', 'Security'],
      image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_15',
      name: 'Rustomjee Elements',
      location: 'Andheri West',
      builder: 'Rustomjee Group',
      price: '₹2.5 Cr - ₹6.8 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 19.1368, lng: 72.8261 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_16',
      name: 'Wadhwa Atmosphere',
      location: 'Mulund West',
      builder: 'Wadhwa Group',
      price: '₹1.8 Cr - ₹4.2 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 19.1728, lng: 72.9345 },
      amenities: ['Swimming Pool', 'Gym', 'Park', 'Security'],
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_17',
      name: 'Mantri Serenity',
      location: 'Kanjurmarg East',
      builder: 'Mantri Developers',
      price: '₹1.5 Cr - ₹3.8 Cr',
      area: '2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 19.1297, lng: 72.9302 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_18',
      name: 'Kanakia Spaces',
      location: 'Mira Road',
      builder: 'Kanakia Group',
      price: '₹95 Lac - ₹2.5 Cr',
      area: '1, 2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 19.2952, lng: 72.8694 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_19',
      name: 'Raymond Realty',
      location: 'Thane West',
      builder: 'Raymond Realty',
      price: '₹1.2 Cr - ₹3.2 Cr',
      area: '2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 19.1972, lng: 72.9720 },
      amenities: ['Swimming Pool', 'Gym', 'Park', 'Security'],
      image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_20',
      name: 'Piramal Mahalaxmi',
      location: 'Mahalaxmi',
      builder: 'Piramal Realty',
      price: '₹8.5 Cr - ₹25 Cr',
      area: '3, 4, 5 BHK',
      status: 'Under Construction',
      coordinates: { lat: 18.9847, lng: 72.8206 },
      amenities: ['Sea View', 'Swimming Pool', 'Spa', 'Concierge'],
      image: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?ixlib=rb-4.0.3'
    }
  ],
  delhi: [
    {
      id: 'delhi_1',
      name: 'DLF The Camellias',
      location: 'Sector 42, Gurgaon',
      builder: 'DLF Limited',
      price: '₹8 Cr - ₹25 Cr',
      area: '3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.4403, lng: 77.0637 },
      amenities: ['Golf Course', 'Swimming Pool', 'Spa', 'Security'],
      image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_2',
      name: 'Godrej South Estate',
      location: 'Sector 150, Noida',
      builder: 'Godrej Properties',
      price: '₹1.2 Cr - ₹3.8 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.5021, lng: 77.4086 },
      amenities: ['Swimming Pool', 'Gym', 'Park', 'Security'],
      image: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_3',
      name: 'M3M Golf Estate',
      location: 'Sector 65, Gurgaon',
      builder: 'M3M Group',
      price: '₹2.5 Cr - ₹8.5 Cr',
      area: '3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.3952, lng: 77.0463 },
      amenities: ['Golf Course', 'Swimming Pool', 'Club House', 'Security'],
      image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_4',
      name: 'Sobha City',
      location: 'Sector 108, Gurgaon',
      builder: 'Sobha Limited',
      price: '₹1.8 Cr - ₹5.2 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.4089, lng: 77.0507 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_5',
      name: 'Emaar Palm Hills',
      location: 'Sector 77, Gurgaon',
      builder: 'Emaar India',
      price: '₹3.2 Cr - ₹9.8 Cr',
      area: '3, 4, 5 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.3894, lng: 77.0683 },
      amenities: ['Swimming Pool', 'Gym', 'Golf Course', 'Security'],
      image: 'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_6',
      name: 'Tata Primanti',
      location: 'Sector 72, Gurgaon',
      builder: 'Tata Housing',
      price: '₹1.5 Cr - ₹4.2 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.3742, lng: 77.0895 },
      amenities: ['Swimming Pool', 'Gym', 'Park', 'Security'],
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_7',
      name: 'Godrej Golf Links',
      location: 'Greater Noida',
      builder: 'Godrej Properties',
      price: '₹85 Lac - ₹2.5 Cr',
      area: '2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.4744, lng: 77.5040 },
      amenities: ['Golf Course', 'Swimming Pool', 'Club House', 'Security'],
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_8',
      name: 'Mahindra Happinest',
      location: 'Palghar',
      builder: 'Mahindra Lifespace',
      price: '₹65 Lac - ₹1.8 Cr',
      area: '1, 2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.5355, lng: 77.3910 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_9',
      name: 'Lodha Upper Thane',
      location: 'Bhiwandi',
      builder: 'Lodha Group',
      price: '₹75 Lac - ₹2.2 Cr',
      area: '1, 2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.6139, lng: 77.2090 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_10',
      name: 'Prestige Jindal City',
      location: 'Tumkur Road',
      builder: 'Prestige Group',
      price: '₹95 Lac - ₹2.8 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.4595, lng: 77.0266 },
      amenities: ['Swimming Pool', 'Gym', 'Park', 'Security'],
      image: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_11',
      name: 'Brigade Meadows',
      location: 'Kanakapura Road',
      builder: 'Brigade Group',
      price: '₹1.2 Cr - ₹3.5 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.6692, lng: 77.4538 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_12',
      name: 'Shapoorji Pallonji Joyville',
      location: 'Sector 102, Gurgaon',
      builder: 'Shapoorji Pallonji',
      price: '₹1.8 Cr - ₹4.5 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.4166, lng: 77.0369 },
      amenities: ['Swimming Pool', 'Gym', 'Park', 'Security'],
      image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_13',
      name: 'Ambience Creacions',
      location: 'Sector 22, Gurgaon',
      builder: 'Ambience Group',
      price: '₹4.5 Cr - ₹12.8 Cr',
      area: '3, 4, 5 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.4817, lng: 77.0756 },
      amenities: ['Swimming Pool', 'Spa', 'Golf Course', 'Concierge'],
      image: 'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_14',
      name: 'Supertech Eco Village',
      location: 'Sector 1, Greater Noida West',
      builder: 'Supertech Limited',
      price: '₹75 Lac - ₹1.8 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.4636, lng: 77.4866 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_15',
      name: 'ATS One Hamlet',
      location: 'Sector 104, Noida',
      builder: 'ATS Infrastructure',
      price: '₹1.5 Cr - ₹4.2 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.5449, lng: 77.3722 },
      amenities: ['Swimming Pool', 'Gym', 'Golf Course', 'Security'],
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_16',
      name: 'Jaypee Greens',
      location: 'Sector 128, Noida',
      builder: 'Jaypee Group',
      price: '₹1.8 Cr - ₹5.2 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.5403, lng: 77.3370 },
      amenities: ['Golf Course', 'Swimming Pool', 'Club House', 'Security'],
      image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_17',
      name: 'Mahagun Moderne',
      location: 'Sector 78, Noida',
      builder: 'Mahagun Group',
      price: '₹2.2 Cr - ₹6.8 Cr',
      area: '3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.5021, lng: 77.3648 },
      amenities: ['Swimming Pool', 'Gym', 'Spa', 'Security'],
      image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_18',
      name: 'Ajnara Daffodil',
      location: 'Sector 137, Noida',
      builder: 'Ajnara Group',
      price: '₹85 Lac - ₹2.5 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.5012, lng: 77.3909 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_19',
      name: 'Gulshan Botnia',
      location: 'Sector 144, Noida',
      builder: 'Gulshan Homz',
      price: '₹95 Lac - ₹2.8 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.5052, lng: 77.4170 },
      amenities: ['Swimming Pool', 'Gym', 'Park', 'Security'],
      image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_20',
      name: 'Paras Tierea',
      location: 'Sector 137, Noida',
      builder: 'Paras Buildtech',
      price: '₹1.2 Cr - ₹3.8 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.4998, lng: 77.3888 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?ixlib=rb-4.0.3'
    }
  ],
  mumbai: [
    {
      id: 'mumbai_1',
      name: 'Lodha Park',
      location: 'Lower Parel',
      builder: 'Lodha Group',
      price: '₹2.5 Cr - ₹8.5 Cr',
      area: '1, 2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 19.0144, lng: 72.8317 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_2',
      name: 'Oberoi Realty Sky City',
      location: 'Worli',
      builder: 'Oberoi Realty',
      price: '₹4.2 Cr - ₹12.5 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 19.0176, lng: 72.8162 },
      amenities: ['Club House', 'Swimming Pool', 'Spa'],
      image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_3',
      name: 'Hiranandani Estate',
      location: 'Thane',
      builder: 'Hiranandani Group',
      price: '₹1.8 Cr - ₹4.5 Cr',
      area: '2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 19.2183, lng: 72.9781 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Children Play Area'],
      image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_4',
      name: 'Tata Housing Primanti',
      location: 'Sector 72, Gurgaon',
      builder: 'Tata Housing',
      price: '₹3.2 Cr - ₹7.8 Cr',
      area: '1, 2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 19.0330, lng: 72.8570 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Security'],
      image: 'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_5',
      name: 'Mahindra Lifespace Windchimes',
      location: 'Kandivali East',
      builder: 'Mahindra Lifespace',
      price: '₹1.5 Cr - ₹3.8 Cr',
      area: '2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 19.2056, lng: 72.8681 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_6',
      name: 'Godrej Properties Emerald',
      location: 'Thane West',
      builder: 'Godrej Properties',
      price: '₹2.1 Cr - ₹5.5 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 19.1972, lng: 72.9722 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Tennis Court'],
      image: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_7',
      name: 'Kalpataru Paramount',
      location: 'Thane',
      builder: 'Kalpataru Group',
      price: '₹1.9 Cr - ₹4.2 Cr',
      area: '2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 19.2147, lng: 72.9714 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_8',
      name: 'Raymond Realty TenX Habitat',
      location: 'Thane West',
      builder: 'Raymond Realty',
      price: '₹2.8 Cr - ₹6.5 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 19.1901, lng: 72.9634 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Spa'],
      image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_9',
      name: 'Piramal Revanta',
      location: 'Mulund West',
      builder: 'Piramal Realty',
      price: '₹3.5 Cr - ₹8.2 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 19.1722, lng: 72.9569 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
    },
    {
      id: 'mumbai_10',
      name: 'Runwal Gardens',
      location: 'Dombivli East',
      builder: 'Runwal Group',
      price: '₹1.2 Cr - ₹2.8 Cr',
      area: '1, 2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 19.2183, lng: 73.0869 },
      amenities: ['Swimming Pool', 'Gym', 'Children Play Area', 'Security'],
      image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3'
    }
  ],
  ghaziabad: [
    {
      id: 'ghaziabad_1',
      name: 'Supertech Cape Town',
      location: 'Sector 74',
      builder: 'Supertech Limited',
      price: '₹85 Lac - ₹1.5 Cr',
      area: '2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.6017, lng: 77.4085 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3'
    },
    {
      id: 'ghaziabad_2',
      name: 'Mahagun Moderne',
      location: 'Sector 78',
      builder: 'Mahagun Group',
      price: '₹95 Lac - ₹2.1 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.6139, lng: 77.4270 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Security'],
      image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3'
    },
    {
      id: 'ghaziabad_3',
      name: 'ATS Pristine',
      location: 'Sector 150',
      builder: 'ATS Infrastructure',
      price: '₹1.2 Cr - ₹2.8 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.6292, lng: 77.3910 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Tennis Court'],
      image: 'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?ixlib=rb-4.0.3'
    },
    {
      id: 'ghaziabad_4',
      name: 'Gaur City 2',
      location: 'Sector 16C',
      builder: 'Gaursons Group',
      price: '₹65 Lac - ₹1.8 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.6127, lng: 77.4238 },
      amenities: ['Swimming Pool', 'Gym', 'Shopping Mall', 'Security'],
      image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3'
    },
    {
      id: 'ghaziabad_5',
      name: 'Ajnara Homes',
      location: 'Sector 16B',
      builder: 'Ajnara India Ltd',
      price: '₹75 Lac - ₹1.6 Cr',
      area: '2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.6200, lng: 77.4100 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?ixlib=rb-4.0.3'
    },
    {
      id: 'ghaziabad_6',
      name: 'SKA Greenarch',
      location: 'Sector 16C',
      builder: 'SKA Group',
      price: '₹88 Lac - ₹2.2 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.6150, lng: 77.4200 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Children Play Area'],
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3'
    },
    {
      id: 'ghaziabad_7',
      name: 'Paramount Emotions',
      location: 'Sector 1',
      builder: 'Paramount Group',
      price: '₹72 Lac - ₹1.9 Cr',
      area: '2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.6089, lng: 77.4156 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?ixlib=rb-4.0.3'
    },
    {
      id: 'ghaziabad_8',
      name: 'Omaxe The Resort',
      location: 'Mullanpur',
      builder: 'Omaxe Limited',
      price: '₹1.1 Cr - ₹2.5 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.6234, lng: 77.4050 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Spa'],
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
    },
    {
      id: 'ghaziabad_9',
      name: 'Nirala Aspire',
      location: 'Sector 16',
      builder: 'Nirala Group',
      price: '₹78 Lac - ₹1.7 Cr',
      area: '2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.6180, lng: 77.4120 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3'
    },
    {
      id: 'ghaziabad_10',
      name: 'Wave City',
      location: 'NH-24',
      builder: 'Wave Infratech',
      price: '₹1.3 Cr - ₹3.2 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.6300, lng: 77.4000 },
      amenities: ['Swimming Pool', 'Gym', 'Golf Course', 'Club House'],
      image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3'
    }
  ],
  noida: [
    {
      id: 'noida_1',
      name: 'Amrapali Silicon City',
      location: 'Sector 76',
      builder: 'Amrapali Group',
      price: '₹45 Lac - ₹1.2 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.5700, lng: 77.3200 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?ixlib=rb-4.0.3'
    },
    {
      id: 'noida_2',
      name: 'Supertech Eco Village',
      location: 'Sector 1',
      builder: 'Supertech Limited',
      price: '₹65 Lac - ₹1.8 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.5355, lng: 77.3910 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Tennis Court'],
      image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3'
    },
    {
      id: 'noida_3',
      name: 'ATS Knightsbridge',
      location: 'Sector 124',
      builder: 'ATS Infrastructure',
      price: '₹1.8 Cr - ₹4.5 Cr',
      area: '3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.5406, lng: 77.3219 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Golf Course'],
      image: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?ixlib=rb-4.0.3'
    },
    {
      id: 'noida_4',
      name: 'Jaypee Greens',
      location: 'Sector 128',
      builder: 'Jaiprakash Associates',
      price: '₹1.2 Cr - ₹3.5 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.5403, lng: 77.3200 },
      amenities: ['Swimming Pool', 'Gym', 'Golf Course', 'Club House'],
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3'
    },
    {
      id: 'noida_5',
      name: 'Godrej Woods',
      location: 'Sector 43',
      builder: 'Godrej Properties',
      price: '₹2.5 Cr - ₹6.8 Cr',
      area: '3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.5562, lng: 77.3410 },
      amenities: ['Swimming Pool', 'Gym', 'Spa', 'Tennis Court'],
      image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?ixlib=rb-4.0.3'
    },
    {
      id: 'noida_6',
      name: 'Mahagun Mywoods',
      location: 'Sector 16C',
      builder: 'Mahagun Group',
      price: '₹1.6 Cr - ₹4.2 Cr',
      area: '3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.5456, lng: 77.3500 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
    },
    {
      id: 'noida_7',
      name: 'Antriksh Heights',
      location: 'Sector 84',
      builder: 'Antriksh India',
      price: '₹75 Lac - ₹2.1 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.5600, lng: 77.3300 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Children Play Area'],
      image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3'
    },
    {
      id: 'noida_8',
      name: 'Prateek Wisteria',
      location: 'Sector 77',
      builder: 'Prateek Group',
      price: '₹95 Lac - ₹2.8 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.5734, lng: 77.3200 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3'
    },
    {
      id: 'noida_9',
      name: 'Lotus Boulevard',
      location: 'Sector 100',
      builder: 'Lotus Realtech',
      price: '₹1.4 Cr - ₹3.9 Cr',
      area: '3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.5367, lng: 77.3700 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Spa'],
      image: 'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?ixlib=rb-4.0.3'
    },
    {
      id: 'noida_10',
      name: 'Stellar Jeevan',
      location: 'Sector 1',
      builder: 'Stellar Group',
      price: '₹58 Lac - ₹1.5 Cr',
      area: '2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.5389, lng: 77.3950 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3'
    }
  ],
  delhi: [
    {
      id: 'delhi_1',
      name: 'DLF The Camellias',
      location: 'Sector 42, Gurgaon',
      builder: 'DLF Limited',
      price: '₹8 Cr - ₹25 Cr',
      area: '3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.4403, lng: 77.0637 },
      amenities: ['Golf Course', 'Swimming Pool', 'Spa', 'Security'],
      image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_2',
      name: 'Godrej Properties',
      location: 'Sector 150, Noida',
      builder: 'Godrej Properties',
      price: '₹1.2 Cr - ₹3.8 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.5021, lng: 77.4086 },
      amenities: ['Swimming Pool', 'Gym', 'Park', 'Security'],
      image: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_3',
      name: 'Tata Housing Primanti',
      location: 'Sector 72, Gurgaon',
      builder: 'Tata Housing',
      price: '₹2.5 Cr - ₹6.8 Cr',
      area: '1, 2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.3753, lng: 77.0538 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Security'],
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_4',
      name: 'M3M Golf Estate',
      location: 'Sector 65, Gurgaon',
      builder: 'M3M Group',
      price: '₹5.2 Cr - ₹15.5 Cr',
      area: '3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.3850, lng: 77.0800 },
      amenities: ['Golf Course', 'Swimming Pool', 'Club House', 'Spa'],
      image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_5',
      name: 'Unitech The Residences',
      location: 'Sector 33, Gurgaon',
      builder: 'Unitech Limited',
      price: '₹3.8 Cr - ₹9.5 Cr',
      area: '3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.4294, lng: 77.0688 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_6',
      name: 'Emaar MGF The Views',
      location: 'Sector 106, Gurgaon',
      builder: 'Emaar MGF',
      price: '₹2.8 Cr - ₹7.2 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.4089, lng: 77.0750 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Tennis Court'],
      image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_7',
      name: 'Ansal Heights',
      location: 'Sector 92, Gurgaon',
      builder: 'Ansal API',
      price: '₹1.8 Cr - ₹4.5 Cr',
      area: '2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.4000, lng: 77.0600 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_8',
      name: 'Ireo Victory Valley',
      location: 'Sector 67, Gurgaon',
      builder: 'Ireo Private Limited',
      price: '₹4.5 Cr - ₹12.8 Cr',
      area: '3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.3900, lng: 77.0700 },
      amenities: ['Golf Course', 'Swimming Pool', 'Spa', 'Club House'],
      image: 'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_9',
      name: 'BPTP Park Serene',
      location: 'Sector 37D, Gurgaon',
      builder: 'BPTP Limited',
      price: '₹2.1 Cr - ₹5.8 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.4200, lng: 77.0650 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Children Play Area'],
      image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3'
    },
    {
      id: 'delhi_10',
      name: 'Sobha International City',
      location: 'Sector 109, Gurgaon',
      builder: 'Sobha Limited',
      price: '₹3.5 Cr - ₹8.9 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.4150, lng: 77.0800 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Security'],
      image: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?ixlib=rb-4.0.3'
    }
  ],
  bangalore: [
    {
      id: 'bangalore_1',
      name: 'Brigade Cornerstone Utopia',
      location: 'Varthur',
      builder: 'Brigade Group',
      price: '₹1.2 Cr - ₹3.8 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 12.9698, lng: 77.7500 },
      amenities: ['Swimming Pool', 'Gym', 'Park', 'Security'],
      image: 'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?ixlib=rb-4.0.3'
    },
    {
      id: 'bangalore_2',
      name: 'Prestige Lakeside Habitat',
      location: 'Varthur',
      builder: 'Prestige Group',
      price: '₹1.8 Cr - ₹4.5 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 12.9716, lng: 77.7946 },
      amenities: ['Lake View', 'Swimming Pool', 'Club House', 'Tennis Court'],
      image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3'
    },
    {
      id: 'bangalore_3',
      name: 'Godrej Reflections',
      location: 'Harlur',
      builder: 'Godrej Properties',
      price: '₹1.5 Cr - ₹3.9 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 12.8970, lng: 77.6934 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3'
    },
    {
      id: 'bangalore_4',
      name: 'Sobha Neopolis',
      location: 'Panathur',
      builder: 'Sobha Limited',
      price: '₹2.2 Cr - ₹5.8 Cr',
      area: '3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 12.9600, lng: 77.6900 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Spa'],
      image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?ixlib=rb-4.0.3'
    },
    {
      id: 'bangalore_5',
      name: 'Mantri Glades',
      location: 'Sarjapur Road',
      builder: 'Mantri Developers',
      price: '₹1.8 Cr - ₹4.2 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 12.9279, lng: 77.6271 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Tennis Court'],
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
    },
    {
      id: 'bangalore_6',
      name: 'Puravankara Zenium',
      location: 'Hosur Road',
      builder: 'Puravankara Limited',
      price: '₹2.5 Cr - ₹6.5 Cr',
      area: '3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 12.9141, lng: 77.6411 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Security'],
      image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3'
    },
    {
      id: 'bangalore_7',
      name: 'Salarpuria Sattva Divinity',
      location: 'Kogilu',
      builder: 'Salarpuria Sattva',
      price: '₹1.4 Cr - ₹3.6 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 13.0827, lng: 77.5946 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Children Play Area'],
      image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3'
    },
    {
      id: 'bangalore_8',
      name: 'Assetz Marq',
      location: 'Kanakpura Road',
      builder: 'Assetz Property Group',
      price: '₹1.6 Cr - ₹4.1 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 12.8546, lng: 77.5679 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Security'],
      image: 'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?ixlib=rb-4.0.3'
    },
    {
      id: 'bangalore_9',
      name: 'Embassy Boulevard',
      location: 'Bagalur',
      builder: 'Embassy Group',
      price: '₹2.8 Cr - ₹7.2 Cr',
      area: '3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 13.0358, lng: 77.6200 },
      amenities: ['Swimming Pool', 'Gym', 'Golf Course', 'Spa'],
      image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3'
    },
    {
      id: 'bangalore_10',
      name: 'Shriram Park 63',
      location: 'Jakkur',
      builder: 'Shriram Properties',
      price: '₹1.3 Cr - ₹3.4 Cr',
      area: '2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 13.0827, lng: 77.6380 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?ixlib=rb-4.0.3'
    }
  ],
  greaternoida: [
    {
      id: 'greaternoida_1',
      name: 'Gaur Yamuna City',
      location: 'Sector 19',
      builder: 'Gaursons Group',
      price: '₹35 Lac - ₹85 Lac',
      area: '1, 2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.4744, lng: 77.5040 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3'
    },
    {
      id: 'greaternoida_2',
      name: 'ATS Allure',
      location: 'Sector 22D',
      builder: 'ATS Infrastructure',
      price: '₹75 Lac - ₹1.8 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.4594, lng: 77.5067 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Tennis Court'],
      image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?ixlib=rb-4.0.3'
    },
    {
      id: 'gurugram_4',
      name: 'Tata Housing Primanti',
      location: 'Sector 72',
      builder: 'Tata Housing',
      price: '₹2.5 Cr - ₹6.8 Cr',
      area: '1, 2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.3753, lng: 77.0538 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Security'],
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3'
    },
    {
      id: 'gurugram_5',
      name: 'Emaar Palm Hills',
      location: 'Sector 77',
      builder: 'Emaar India',
      price: '₹3.2 Cr - ₹8.9 Cr',
      area: '3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.3800, lng: 77.0700 },
      amenities: ['Swimming Pool', 'Gym', 'Golf Course', 'Club House'],
      image: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?ixlib=rb-4.0.3'
    },
    {
      id: 'gurugram_6',
      name: 'Ireo Victory Valley',
      location: 'Sector 67',
      builder: 'Ireo Private Limited',
      price: '₹4.5 Cr - ₹12.8 Cr',
      area: '3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.3900, lng: 77.0700 },
      amenities: ['Golf Course', 'Swimming Pool', 'Spa', 'Club House'],
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
    },
    {
      id: 'gurugram_7',
      name: 'BPTP Park Serene',
      location: 'Sector 37D',
      builder: 'BPTP Limited',
      price: '₹2.1 Cr - ₹5.8 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.4200, lng: 77.0650 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Children Play Area'],
      image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3'
    },
    {
      id: 'gurugram_8',
      name: 'Unitech The Residences',
      location: 'Sector 33',
      builder: 'Unitech Limited',
      price: '₹3.8 Cr - ₹9.5 Cr',
      area: '3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.4294, lng: 77.0688 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3'
    },
    {
      id: 'gurugram_9',
      name: 'Sobha International City',
      location: 'Sector 109',
      builder: 'Sobha Limited',
      price: '₹3.5 Cr - ₹8.9 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 28.4150, lng: 77.0800 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Security'],
      image: 'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?ixlib=rb-4.0.3'
    },
    {
      id: 'gurugram_10',
      name: 'Ansal Heights',
      location: 'Sector 92',
      builder: 'Ansal API',
      price: '₹1.8 Cr - ₹4.5 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 28.4000, lng: 77.0600 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3'
    }
  ],
  chandigarh: [
    {
      id: 'chandigarh_1',
      name: 'Omaxe The Resort',
      location: 'Mullanpur',
      builder: 'Omaxe Limited',
      price: '₹85 Lac - ₹2.2 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 30.7333, lng: 76.7794 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Security'],
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3'
    },
    {
      id: 'chandigarh_2',
      name: 'DLF New Town Heights',
      location: 'Sector 90',
      builder: 'DLF Limited',
      price: '₹1.2 Cr - ₹3.5 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 30.6942, lng: 76.7786 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Tennis Court'],
      image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?ixlib=rb-4.0.3'
    },
    {
      id: 'chandigarh_3',
      name: 'Godrej Nurture',
      location: 'Sector 103',
      builder: 'Godrej Properties',
      price: '₹75 Lac - ₹1.9 Cr',
      area: '2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 30.6900, lng: 76.7800 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
    },
    {
      id: 'chandigarh_4',
      name: 'Tata Housing Avenida',
      location: 'New Chandigarh',
      builder: 'Tata Housing',
      price: '₹95 Lac - ₹2.8 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 30.7000, lng: 76.7700 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Spa'],
      image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3'
    },
    {
      id: 'chandigarh_5',
      name: 'Ansal API Golf Links',
      location: 'Sector 114',
      builder: 'Ansal API',
      price: '₹1.1 Cr - ₹3.2 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 30.6850, lng: 76.7850 },
      amenities: ['Golf Course', 'Swimming Pool', 'Club House', 'Security'],
      image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3'
    },
    {
      id: 'chandigarh_6',
      name: 'Emaar The Palm Springs',
      location: 'Sector 54',
      builder: 'Emaar MGF',
      price: '₹1.8 Cr - ₹4.5 Cr',
      area: '3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 30.7100, lng: 76.7600 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Tennis Court'],
      image: 'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?ixlib=rb-4.0.3'
    },
    {
      id: 'chandigarh_7',
      name: 'BPTP Parklands',
      location: 'Sector 76',
      builder: 'BPTP Limited',
      price: '₹68 Lac - ₹1.6 Cr',
      area: '2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 30.6950, lng: 76.7750 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?ixlib=rb-4.0.3'
    },
    {
      id: 'chandigarh_8',
      name: 'Vatika City Homes',
      location: 'Sector 83',
      builder: 'Vatika Group',
      price: '₹72 Lac - ₹1.8 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 30.6800, lng: 76.7900 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Children Play Area'],
      image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3'
    },
    {
      id: 'chandigarh_9',
      name: 'Puri Emerald Bay',
      location: 'Sector 104',
      builder: 'Puri Construction',
      price: '₹88 Lac - ₹2.1 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 30.6900, lng: 76.7800 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Security'],
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3'
    },
    {
      id: 'chandigarh_10',
      name: 'Gillco Valley',
      location: 'Sector 127',
      builder: 'Gillco Group',
      price: '₹58 Lac - ₹1.4 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 30.6750, lng: 76.7950 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?ixlib=rb-4.0.3'
    }
  ],
  chennai: [
    {
      id: 'chennai_1',
      name: 'Godrej Oasis',
      location: 'Sector 88A',
      builder: 'Godrej Properties',
      price: '₹85 Lac - ₹2.1 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 13.0827, lng: 80.2707 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
    },
    {
      id: 'chennai_2',
      name: 'Prestige Tranquility',
      location: 'Budigere Cross',
      builder: 'Prestige Group',
      price: '₹1.2 Cr - ₹3.5 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 13.0358, lng: 80.2772 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Tennis Court'],
      image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3'
    },
    {
      id: 'chennai_3',
      name: 'Sobha Dream Acres',
      location: 'Thanisandra',
      builder: 'Sobha Limited',
      price: '₹1.8 Cr - ₹4.2 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 13.0827, lng: 80.2500 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Spa'],
      image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3'
    },
    {
      id: 'chennai_4',
      name: 'Brigade Cornerstone Utopia',
      location: 'Varthur',
      builder: 'Brigade Group',
      price: '₹95 Lac - ₹2.8 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 13.0600, lng: 80.2400 },
      amenities: ['Swimming Pool', 'Gym', 'Park', 'Security'],
      image: 'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?ixlib=rb-4.0.3'
    },
    {
      id: 'chennai_5',
      name: 'Puravankara Purva Windermere',
      location: 'Pallavaram',
      builder: 'Puravankara Limited',
      price: '₹75 Lac - ₹1.9 Cr',
      area: '2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 12.9676, lng: 80.1482 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3'
    },
    {
      id: 'chennai_6',
      name: 'Shriram Grand City',
      location: 'Chengalpattu',
      builder: 'Shriram Properties',
      price: '₹42 Lac - ₹1.2 Cr',
      area: '1, 2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 12.6921, lng: 80.0437 },
      amenities: ['Swimming Pool', 'Gym', 'Shopping Mall', 'Security'],
      image: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?ixlib=rb-4.0.3'
    },
    {
      id: 'chennai_7',
      name: 'Mantri Glades',
      location: 'Sarjapur Road',
      builder: 'Mantri Developers',
      price: '₹1.1 Cr - ₹2.9 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 13.0100, lng: 80.2300 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Tennis Court'],
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3'
    },
    {
      id: 'chennai_8',
      name: 'Salarpuria Sattva Greenage',
      location: 'Sholinganallur',
      builder: 'Salarpuria Sattva',
      price: '₹88 Lac - ₹2.4 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 12.9010, lng: 80.2279 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?ixlib=rb-4.0.3'
    },
    {
      id: 'chennai_9',
      name: 'Embassy Boulevard',
      location: 'Perumbakkam',
      builder: 'Embassy Group',
      price: '₹1.5 Cr - ₹3.8 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 12.9165, lng: 80.2379 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Spa'],
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
    },
    {
      id: 'chennai_10',
      name: 'Mahindra Lifespace Bloomdale',
      location: 'Mihan',
      builder: 'Mahindra Lifespace',
      price: '₹65 Lac - ₹1.6 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 12.9500, lng: 80.2200 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Children Play Area'],
      image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3'
    }
  ],
  kolkata: [
    {
      id: 'kolkata_1',
      name: 'Godrej Prakriti',
      location: 'Sodepur',
      builder: 'Godrej Properties',
      price: '₹45 Lac - ₹1.2 Cr',
      area: '2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 22.5726, lng: 88.3639 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3'
    },
    {
      id: 'kolkata_2',
      name: 'Prestige Song of the South',
      location: 'Begur Road',
      builder: 'Prestige Group',
      price: '₹65 Lac - ₹1.8 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 22.5400, lng: 88.3500 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Tennis Court'],
      image: 'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?ixlib=rb-4.0.3'
    },
    {
      id: 'kolkata_3',
      name: 'Sobha City',
      location: '108 Southern Avenue',
      builder: 'Sobha Limited',
      price: '₹88 Lac - ₹2.1 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 22.5200, lng: 88.3600 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3'
    },
    {
      id: 'kolkata_4',
      name: 'Shriram Chirping Woods',
      location: 'New Town',
      builder: 'Shriram Properties',
      price: '₹52 Lac - ₹1.4 Cr',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 22.5900, lng: 88.4700 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Children Play Area'],
      image: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?ixlib=rb-4.0.3'
    },
    {
      id: 'kolkata_5',
      name: 'Brigade Cosmopolis',
      location: 'Rajarhat',
      builder: 'Brigade Group',
      price: '₹75 Lac - ₹1.9 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 22.5800, lng: 88.4600 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Tennis Court'],
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3'
    },
    {
      id: 'kolkata_6',
      name: 'Salarpuria Sattva Greenage',
      location: 'Madhyamgram',
      builder: 'Salarpuria Sattva',
      price: '₹38 Lac - ₹95 Lac',
      area: '2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 22.7000, lng: 88.4500 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?ixlib=rb-4.0.3'
    },
    {
      id: 'kolkata_7',
      name: 'Ramky One Galaxia',
      location: 'Barasat',
      builder: 'Ramky Group',
      price: '₹42 Lac - ₹1.1 Cr',
      area: '2, 3 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 22.7200, lng: 88.4800 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Security'],
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
    },
    {
      id: 'kolkata_8',
      name: 'Lodha Belmondo',
      location: 'Howrah',
      builder: 'Lodha Group',
      price: '₹58 Lac - ₹1.6 Cr',
      area: '2, 3, 4 BHK',
      status: 'Under Construction',
      coordinates: { lat: 22.5958, lng: 88.2636 },
      amenities: ['Swimming Pool', 'Gym', 'Club House', 'Spa'],
      image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3'
    },
    {
      id: 'kolkata_9',
      name: 'Tata Housing New Haven',
      location: 'Rajarhat',
      builder: 'Tata Housing',
      price: '₹68 Lac - ₹1.8 Cr',
      area: '2, 3, 4 BHK',
      status: 'Ready to Move',
      coordinates: { lat: 22.5850, lng: 88.4650 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Security'],
      image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3'
    },
    {
      id: 'kolkata_10',
      name: 'Mahindra Lifespace Bloomdale',
      location: 'Joka',
      builder: 'Mahindra Lifespace',
      price: '₹35 Lac - ₹85 Lac',
      area: '1, 2, 3 BHK',
      status: 'Under Construction',
      coordinates: { lat: 22.4500, lng: 88.3200 },
      amenities: ['Swimming Pool', 'Gym', 'Garden', 'Children Play Area'],
      image: 'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?ixlib=rb-4.0.3'
    }
  ],
  gurgaon: [
  {
    id: 'gurgaon-1',
    name: 'DLF Magnolias',
    location: 'Golf Course Road',
    builder: 'DLF Limited',
    price: '₹4.5 Cr - ₹12 Cr',
    area: '3, 4 BHK',
    status: 'Ready to Move',
    coordinates: { lat: 28.4595, lng: 77.0266 },
    amenities: ['Swimming Pool', 'Golf Course', 'Club House', '24/7 Security', 'Spa'],
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
  },
  {
    id: 'gurgaon-2',
    name: 'Godrej Summit',
    location: 'Sector 104',
    builder: 'Godrej Properties',
    price: '₹1.8 Cr - ₹3.5 Cr',
    area: '2, 3 BHK',
    status: 'Under Construction',
    coordinates: { lat: 28.4089, lng: 77.0648 },
    amenities: ['Swimming Pool', 'Gym', 'Children Play Area', 'Security', 'Power Backup'],
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
  },
  {
    id: 'gurgaon-3',
    name: 'Emaar Palm Drive',
    location: 'Sector 66',
    builder: 'Emaar India',
    price: '₹2.2 Cr - ₹4.8 Cr',
    area: '2, 3, 4 BHK',
    status: 'Ready to Move',
    coordinates: { lat: 28.3927, lng: 77.0636 },
    amenities: ['Swimming Pool', 'Tennis Court', 'Gym', 'Garden', 'Security'],
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
  },
  {
    id: 'gurgaon-4',
    name: 'M3M Golf Estate',
    location: 'Sector 65',
    builder: 'M3M Group',
    price: '₹3.8 Cr - ₹9.5 Cr',
    area: '3, 4, 5 BHK',
    status: 'Ready to Move',
    coordinates: { lat: 28.3952, lng: 77.0462 },
    amenities: ['Golf Course', 'Swimming Pool', 'Club House', 'Gym', 'Concierge'],
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
  },
  {
    id: 'gurgaon-5',
    name: 'Tata Primanti',
    location: 'Sector 72',
    builder: 'Tata Housing',
    price: '₹1.5 Cr - ₹2.8 Cr',
    area: '1, 2, 3 BHK',
    status: 'Ready to Move',
    coordinates: { lat: 28.3844, lng: 77.0674 },
    amenities: ['Swimming Pool', 'Gym', 'Jogging Track', 'Security', 'Shopping Complex'],
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
  },
  {
    id: 'gurgaon-6',
    name: 'BPTP Park Prime',
    location: 'Sector 77',
    builder: 'BPTP Limited',
    price: '₹85 Lakh - ₹1.8 Cr',
    area: '2, 3 BHK',
    status: 'Under Construction',
    coordinates: { lat: 28.3689, lng: 77.0693 },
    amenities: ['Swimming Pool', 'Gym', 'Children Play Area', 'Security', 'Garden'],
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
  },
  {
    id: 'gurgaon-7',
    name: 'Experion The Heartsong',
    location: 'Sector 108',
    builder: 'Experion Developers',
    price: '₹1.2 Cr - ₹2.5 Cr',
    area: '2, 3 BHK',
    status: 'Ready to Move',
    coordinates: { lat: 28.3987, lng: 77.0712 },
    amenities: ['Swimming Pool', 'Gym', 'Multi-purpose Hall', 'Security', 'Landscaped Gardens'],
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
  },
  {
    id: 'gurgaon-8',
    name: 'Sobha City',
    location: 'Sector 108',
    builder: 'Sobha Limited',
    price: '₹1.8 Cr - ₹4.2 Cr',
    area: '2, 3, 4 BHK',
    status: 'Under Construction',
    coordinates: { lat: 28.4012, lng: 77.0701 },
    amenities: ['Swimming Pool', 'Club House', 'Gym', 'Security', 'Retail Spaces'],
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
  },
  {
    id: 'gurgaon-9',
    name: 'Aipl Joy District',
    location: 'Sector 88',
    builder: 'AIPL',
    price: '₹95 Lakh - ₹2.1 Cr',
    area: '1, 2, 3 BHK',
    status: 'Ready to Move',
    coordinates: { lat: 28.3756, lng: 77.0823 },
    amenities: ['Swimming Pool', 'Gym', 'Community Center', 'Security', 'Green Spaces'],
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
  },
  {
    id: 'gurgaon-10',
    name: 'SS The Coralwood',
    location: 'Sector 84',
    builder: 'SS Group',
    price: '₹1.6 Cr - ₹3.2 Cr',
    area: '2, 3, 4 BHK',
    status: 'Under Construction',
    coordinates: { lat: 28.3678, lng: 77.0756 },
    amenities: ['Swimming Pool', 'Gym', 'Yoga Deck', 'Security', 'Children Play Area'],
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3'
  }
]
}

export async function GET(request, { params }) {
  console.log('API Route Hit:', params) // Debug log
  
  const { cityName } = params
  
  if (!cityName) {
    return NextResponse.json({ error: 'City name is required' }, { status: 400 })
  }

  try {
    // Add a small delay to simulate real API call
    await new Promise(resolve => setTimeout(resolve, 1000))
    
    // Get projects for the city (convert to lowercase for matching)
    const projects = mockProjects[cityName.toLowerCase()] || []
    
    console.log(`Found ${projects.length} projects for ${cityName}`) // Debug log
    
    return NextResponse.json({
      projects,
      message: `Found ${projects.length} projects in ${cityName}`,
      success: true,
      city: cityName,
      count: projects.length
    })
  } catch (error) {
    console.error('API Error:', error)
    return NextResponse.json({
      error: 'Failed to fetch projects',
      details: error.message
    }, { status: 500 })
  }
}

// Handle other HTTP methods
export async function POST(request) {
  return NextResponse.json(
    { error: 'Method not allowed' },
    { status: 405 }
  )
}

export async function PUT(request) {
  return NextResponse.json(
    { error: 'Method not allowed' },
    { status: 405 }
  )
}

export async function DELETE(request) {
  return NextResponse.json(
    { error: 'Method not allowed' },
    { status: 405 }
  )
}